# Generated by Django 4.1.1 on 2022-11-05 10:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0016_alter_feed_created_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feed',
            old_name='caption',
            new_name='captionimg',
        ),
        migrations.AddField(
            model_name='feed',
            name='captionvid',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='feed',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 5, 18, 23, 46, 332678)),
        ),
    ]
