# Generated by Django 4.1 on 2022-11-07 04:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0017_rename_caption_feed_captionimg_feed_captionvid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feed',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 7, 12, 27, 19, 983146)),
        ),
    ]
