# Generated by Django 4.1 on 2022-11-15 04:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0039_alter_feed_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='feed',
            name='like_stat',
            field=models.CharField(default='bi bi-heart-fill', max_length=200),
        ),
        migrations.AlterField(
            model_name='feed',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 15, 12, 10, 18, 775219)),
        ),
    ]
