# Generated by Django 4.1 on 2022-11-15 04:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0040_feed_like_stat_alter_feed_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feed',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 15, 12, 12, 2, 819309)),
        ),
        migrations.AlterField(
            model_name='feed',
            name='like_stat',
            field=models.CharField(default='bi bi-heart', max_length=200),
        ),
    ]
