# Generated by Django 4.1 on 2022-11-15 04:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0041_alter_feed_created_at_alter_feed_like_stat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feed',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 15, 12, 15, 22, 157178)),
        ),
    ]
