# Generated by Django 4.1 on 2022-11-15 07:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0044_alter_feed_created_at_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feed',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 15, 15, 33, 57, 562784)),
        ),
    ]
