# Generated by Django 4.1 on 2022-11-04 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prof', '0007_alter_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='blank.png', upload_to='profile_images'),
        ),
    ]
