# Generated by Django 4.1 on 2022-11-08 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0023_alter_feed_created_at_alter_feed_user'),
        ('prof', '0008_alter_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='saved',
            field=models.ManyToManyField(blank=True, related_name='Profile', to='feed.feed'),
        ),
    ]
