# Generated by Django 4.1 on 2022-11-08 03:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('prof', '0008_alter_profile_image'),
        ('tools', '0002_rembg_output'),
    ]

    operations = [
        migrations.AddField(
            model_name='rembg',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='prof.profile'),
            preserve_default=False,
        ),
    ]
