# Generated by Django 4.1 on 2022-11-08 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0004_alter_rembg_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rembg',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='rembg'),
        ),
        migrations.AlterField(
            model_name='rembg',
            name='output',
            field=models.ImageField(blank=True, null=True, upload_to='rembg'),
        ),
    ]
