# Generated by Django 4.1 on 2022-11-11 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0008_word'),
    ]

    operations = [
        migrations.AddField(
            model_name='word',
            name='input',
            field=models.FileField(blank=True, null=True, upload_to='word'),
        ),
    ]
