# Generated by Django 4.1.1 on 2022-11-12 04:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0009_word_input'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='word',
            name='user',
        ),
        migrations.RemoveField(
            model_name='yt',
            name='user',
        ),
        migrations.RemoveField(
            model_name='ytvidmp',
            name='user',
        ),
        migrations.DeleteModel(
            name='Rembg',
        ),
        migrations.DeleteModel(
            name='Word',
        ),
        migrations.DeleteModel(
            name='Yt',
        ),
        migrations.DeleteModel(
            name='Ytvidmp',
        ),
    ]
