# Generated by Django 4.1.1 on 2022-11-12 05:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('prof', '0009_alter_profile_saved'),
        ('tools', '0010_remove_word_user_remove_yt_user_remove_ytvidmp_user_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='wolf',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('output', models.TextField(blank=True, max_length=1000, null=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='prof.profile')),
            ],
        ),
    ]
