# Generated by Django 4.1.1 on 2022-11-12 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0011_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='wolf',
            name='quest',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
    ]
