# Generated by Django 4.1.1 on 2022-11-12 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0012_wolf_quest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wolf',
            name='quest',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
