# Generated by Django 4.1.1 on 2022-11-13 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0013_alter_wolf_quest'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wolf',
            old_name='output',
            new_name='outputtext',
        ),
        migrations.AddField(
            model_name='wolf',
            name='outputimg',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
