# Generated by Django 4.1 on 2022-11-15 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0016_wikihow'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wikihow',
            name='outputtext',
        ),
        migrations.AddField(
            model_name='wikihow',
            name='id_title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='wikihow',
            name='title',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
