# Generated by Django 4.1 on 2022-11-15 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0017_remove_wikihow_outputtext_wikihow_id_title_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='wikihow',
            name='html',
            field=models.TextField(blank=True, max_length=100000, null=True),
        ),
    ]
