# Generated by Django 4.1 on 2022-11-16 04:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('prof', '0009_alter_profile_saved'),
        ('tools', '0019_wolfweather_wolfmath'),
    ]

    operations = [
        migrations.CreateModel(
            name='Qr',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qr', models.CharField(blank=True, max_length=500, null=True)),
                ('res', models.ImageField(blank=True, null=True, upload_to='qr')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='prof.profile')),
            ],
        ),
    ]
