# Generated by Django 4.1 on 2022-11-21 08:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('prof', '0009_alter_profile_saved'),
        ('tools', '0027_alter_xcel2csv_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='xcel2csv',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='xcel'),
        ),
        migrations.CreateModel(
            name='Mp324',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(blank=True, null=True, upload_to='mp3')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='prof.profile')),
            ],
        ),
    ]
